### ISSUE TITLE
Improvement in "PostVideoLarge" Canvas in  our Cards section 

### ISSUE THREAD

**Issue by neeraj-2** [cc-archive/vocabulary-legacy#834] opened 2020-12-14 11:20 UTC
## Problem

The `PostVideoLarge` Canvas does not look good in mobile views.

## Reproduction

1. Either open the website on mobile or click on inspect element on desktop
2. Go to the `Sidebar` section and then click on the `Cards` section
3. Click on the `PostVideoLarge` tab and see the view in the `Canvas` section

## Alternatives

It would be better if we can improvise this `PostVideoLarge` canvas in mobile-version.

## Screenshots

![image](https://user-images.githubusercontent.com/56186425/102079417-b0c63a00-3e32-11eb-8955-246cfc0bcb48.png)

## Implementation

- [ ] I would try to implement the feature if this is a valid issue.

**Comment by nimishbongale** [comment] 2020-12-17 08:19
@neeraj-2 

How do you plan on resolving this issue? All our large cards have a certain width, and are meant to be used on larger screens if I'm not mistaken.

**Comment by manpoffc** [comment] 2021-01-06 08:08
Hi, I wanted to ask if you want to change the PostVideoLarge dynamically when the size of the window changes?

**Comment by neeraj-2** [comment] 2021-01-06 09:08
I was thinking of something we can do, like if we have a mobile screen then we can show a minimized view of the same canvas. Not pretty sure about this. Any suggestions @nimishbongale?

**Comment by nimishbongale** [comment] 2021-01-06 14:20
I'm not entirely certain what needs to be done here.

The width isn't exactly _fixed_ for the component. It occupies a little less than the width of the viewport. We already have viewports configured to view the components at different resolutions. Here's how:

![issue](https://user-images.githubusercontent.com/43414361/103777847-7af22b00-5057-11eb-9fa7-7d2234aa5f14.png)

While the component _may not_ look the best at smaller resolutions, I'm not sure what the component should look like on smaller screens. My best guess is that it should either become a VideoVertical card or just have a smaller size in general.

**Comment by frappelatte28** [comment] 2021-02-18 20:26
Hi, @kgodey @nimishbongale I am not able to reproduce it in my local environment, can you tell me why so? 
I would like to work on this issue.

**Comment by nimishbongale** [comment] 2021-02-19 02:29
@frappelatte28 

Are you not able to run the whole repository or this specific page? Tagging @zackkrida here to confirm if this is a non-issue?

**Comment by frappelatte28** [comment] 2021-02-19 06:47
@nimishbongale I am able to see some of the features only have I done any mistake in the installation process?
![CC](https://user-images.githubusercontent.com/64382399/108468212-62a73a00-72ac-11eb-8d78-4fa23e7cc1e1.png)

**Comment by nimishbongale** [comment] 2021-02-19 07:36
@frappelatte28 PostVideoLarge is a part of Vocabulary and not Vue Vocabulary; so you may have to open `localhost:8081` instead.

**Comment by frappelatte28** [comment] 2021-02-19 08:30
oh okay! my bad.

**Comment by zackkrida** [comment] 2021-02-19 19:09
Hi all, the large post video component should stack on mobile, like so:

<img width="462" alt="2021-02-19-147" src="https://user-images.githubusercontent.com/6351754/108550110-31217500-7292-11eb-8ab9-634c8c6f7b6d.png">

If anyone wants to work on this, just let me know! Thanks.

**Comment by frappelatte28** [comment] 2021-02-20 04:09
Yes, @zackkrida I do want to work on this issue. And can we use "srcset" for the same? we can provide browser 3 different URLs and width of each image via srcset attribute then the brower will be able to choose the best image based on the actual viewport width.
[Here](https://blog.imagekit.io/how-to-deliver-responsive-images-to-browsers-across-multiple-devices-30cfae17390e) is the blog for the same if someone wants to know how to use "srcset" to make images responsive.

**Closed as completed** 2021-03-05 20:12 UTC
Labels: 🟩 priority: low, 🚦 status: awaiting triage, ✨ goal: improvement, 💻 aspect: code
